# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PJ2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

import image


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 1080)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 380, 160, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setMaximum(2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        
        
        #LOGO
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(800, 20, 225, 200))
        self.label_1.setStyleSheet("background-image: url(:/newPrefix/Image/logo.png);")
        self.label_1.setText("")
        self.label_1.setObjectName("label")
        
       
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 160, 121, 121))
        self.label.setStyleSheet("background-image: url(:/newPrefix/Image/bulb_off.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 160, 131, 121))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/Image/door_lock1.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 380, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 160, 131, 131))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/Image/fan_off.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 800, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        #TEMP
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(600, 430, 551, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        #HUMI
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(320, 430, 551, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        #LUX
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 430, 551, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        #AQI
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(800, 430, 551, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")


       

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 380, 75, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 380, 75, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
         
        
        # ===== Biểu đồ =====
        self.figure = Figure()
        self.canvas = FigureCanvas(self.figure)
        self.canvas.setParent(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(30, 550, 1000, 500))

        self.ax = self.figure.add_subplot(111)

        self.temp_data = []
        self.hum_data = []
        self.AQI_data = []

      # ===== Timer 1.5s =====
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_chart)
        self.timer.start(1500)  # 1.5 giây

 
        self.horizontalSlider.valueChanged[int].connect(self.den)
        self.pushButton.setStyleSheet("background-color : lightgrey")
        self.pushButton.setCheckable(True)
        self.pushButton.clicked.connect(self.door)
        self.pushButton_2.clicked.connect(self.fan_on) 
        self.pushButton_3.clicked.connect(self.fan_off) 
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "LOCK/UNLOCK"))
        self.label_6.setText(_translate("MainWindow", "PHẠM TRÍ TÂN-23119104"))
        self.label_9.setText(_translate("MainWindow","Độ sáng: 0 LUX"))
        self.pushButton_2.setText(_translate("MainWindow", "ON"))
        self.pushButton_3.setText(_translate("MainWindow", "OFF"))
    def fan_on(self):
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/Image/fan_on.png);")
    def fan_off(self):
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/Image/fan_off.png);")    
    
    def den(self, value):   
        if value == 0:
            self.label.setStyleSheet("background-image: url(:/newPrefix/Image/bulb_off.png);") 
            self.label_9.setText("Độ sáng: 0 LUX")
        elif value ==1:
            self.label.setStyleSheet("background-image: url(:/newPrefix/Image/light_on1.png);") 
            self.label_9.setText("Độ sáng: 300 LUX")
        elif value ==2:
            self.label.setStyleSheet("background-image: url(:/newPrefix/Image/light_on2.png);") 
            self.label_9.setText("Độ sáng: 500 LUX")
    
    def door(self):
        if self.pushButton.isChecked():
            self.pushButton.setStyleSheet("background-color : lightblue")
            self.label_2.setStyleSheet("background-image: url(:/newPrefix/Image/door_unlock.png);")
        else: 
            self.pushButton.setStyleSheet("background-color : lightgrey")
            self.label_2.setStyleSheet("background-image: url(:/newPrefix/Image/door_lock1.png);")   
    def update_chart(self):
        temp = random.randint(20, 25)
        hum = random.randint(70, 90)
        AQI = random.randint(65, 130)
        
        self.label_7.setText(f"Nhiệt độ:{temp}(°C)")
        self.label_8.setText(f"Độ ẩm:{hum}(%)")
        self.label_10.setText(f"Không khí:{AQI}(AQI)")
        

        self.temp_data.append(temp) 
        self.hum_data.append(hum)
        self.AQI_data.append(AQI)

    
        if len(self.temp_data) > 10:
         self.temp_data.pop(0)
         self.hum_data.pop(0)
         self.AQI_data.pop(0)

        self.ax.clear()
        self.ax.plot(self.temp_data, label="Temp (°C)")
        self.ax.plot(self.hum_data, label="Hum (%)")
        self.ax.plot(self.AQI_data, label = "AQI")
        self.ax.legend()
        self.canvas.draw()


    


    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
